title: Basem Khirat
description: >
  **I am Basem**, a web developer.
copyright: basemkhirat
image: "images/basemkhirat.png"
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: basem-khirat
facebook_username: "basemdev"
twitter_username: "basemkhirat"
linkedin_username:
instagram_username:
pinterest_username:
flickr_username:
github_username:  "basemkhirat"
feed_icon: rss
email: "basemkhirat@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5

github:
  url: http://basemkhirat.com